# -*- coding: utf-8 -*-
"""AIML_Boosting_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j215mkxA4l3hMRluaWmGklfKV7q4t8J4

# AIML Project: High-Performance Prediction (Boosting)
## Gradient Boosting Classifier Implementation
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.ensemble import GradientBoostingClassifier

"""## Load Dataset

"""

df = sns.load_dataset('titanic')
df.head()

"""## Data Exploration

"""

df.info()
print("\nClass Distribution:")
print(df['survived'].value_counts())

"""## Data Preprocessing

"""

df = df[['survived','pclass','sex','age','sibsp','parch','fare','embarked']]

df['age'].fillna(df['age'].mean(), inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

df.head()

"""## Train-Test Split

"""

X = df.drop('survived', axis=1)
y = df['survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""## Model Training

"""

model = GradientBoostingClassifier()
model.fit(X_train, y_train)

"""## Predictions

"""

y_pred = model.predict(X_test)

"""## Evaluation

"""

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

"""## Feature Importance

"""

importances = model.feature_importances_
features = X.columns

plt.figure()
plt.barh(features, importances)
plt.xlabel("Importance")
plt.ylabel("Features")
plt.title("Feature Importance")
plt.show()

"""## Hyperparameter Tuning

"""

model_tuned = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=3
)

model_tuned.fit(X_train, y_train)

y_pred_tuned = model_tuned.predict(X_test)

print("Tuned Accuracy:", accuracy_score(y_test, y_pred_tuned))

"""## Conclusion
- Gradient Boosting improves performance by combining weak learners.
- Increasing estimators improved accuracy.
- Important features include fare and age.


"""