# -*- coding: utf-8 -*-
"""Cafe_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MEdeQi2k3HOba_xF5Npshzj8TryKS3Zl

# ☕ Cafe Sales - Dirty Data Cleaning & EDA
## Kaggle Dataset: Cafe Sales - Dirty Data for Cleaning
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# List files in the downloaded directory to check the correct filename
print(os.listdir(path))

df = pd.read_csv(os.path.join(path, 'dirty_cafe_sales.csv'))
df.head()

"""## 🔍 Data Inspection"""

df.info()
df.describe(include='all')

print(df.dtypes)

"""## 🧹 Data Cleaning"""

# 1. Remove duplicates
print("Duplicates before:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicates after:", df.duplicated().sum())


# 2. Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')


# 3. Replace dirty values
df = df.replace(['ERROR', 'UNKNOWN', '', 'NA', 'null'], np.nan)


# 4. Convert numeric columns safely
numeric_cols = ['quantity', 'price_per_unit', 'total_spent']

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')


# 5. Fix logical inconsistencies
# Recalculate total_spent if possible
if all(col in df.columns for col in ['quantity', 'price_per_unit']):
    df['total_spent'] = df['quantity'] * df['price_per_unit']


# 6. Handle missing values

# Numeric → median
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].median())

# Categorical → mode
for col in df.select_dtypes(include='object'):
    df[col] = df[col].fillna(df[col].mode()[0])


# 7. Final check
print("\nFinal Missing Values:\n", df.isnull().sum())
print("\nData Types:\n", df.dtypes)

"""## ⚙️ Feature Engineering"""

# 1. Recalculate total
if all(col in df.columns for col in ['quantity', 'price_per_unit']):
    df['total_spent'] = df['quantity'] * df['price_per_unit']


# 2. Date processing
# Use 'transaction_date' column, as identified from previous steps
if 'transaction_date' in df.columns:

    # Rename 'transaction_date' to 'date' for consistency within this block
    df['date'] = df['transaction_date']

    # Convert to datetime
    df['date'] = pd.to_datetime(df['date'], errors='coerce')

    # Handle missing dates - fill with the next valid observation
    df['date'] = df['date'].ffill()

    # Extract features
    df['day'] = df['date'].dt.day_name()
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt.year


# 3. Final check
print("\nSample Data:\n", df[['date','day','month','year']].head())

"""## 📦 Outlier Detection (IQR)"""

plt.figure(figsize=(10,5))
sns.boxplot(data=df.select_dtypes(include=np.number))
plt.show()

for col in df.select_dtypes(include=np.number):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]

"""## 🔢 Encoding"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

df.dtypes

"""## 📊 Visual Analysis"""

# Top selling items
if 'item' in df.columns:
    df['item'].value_counts().head(10).plot(kind='bar')
    plt.title('Top Selling Items')
    plt.show()

# Boxplot
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))
sns.boxplot(data=df.select_dtypes(include=np.number))
plt.title("Boxplot for Outlier Detection")
plt.show()


# IQR calculation + removal
for col in df.select_dtypes(include=np.number):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    print(f"{col} → Lower: {lower}, Upper: {upper}")

    df = df[(df[col] >= lower) & (df[col] <= upper)]

print("Outliers removed successfully")

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

print("\nUpdated Data Types:\n", df.dtypes)

df.hist(figsize=(10,8))
plt.suptitle("Distribution of Data")
plt.show()

sns.scatterplot(x=df['quantity'], y=df['total_spent'])
plt.title("Quantity vs Total Spent")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Sales by day
if 'day' in df.columns:
    df.groupby('day')['total_spent'].sum().plot(kind='bar')
    plt.title('Sales by Day')
    plt.show()

print("\n📌 FINAL INSIGHTS:")

print("1. Quantity strongly influences total revenue.")
print("2. Certain items dominate sales across transactions.")
print("3. Sales are higher on specific days, showing temporal trends.")

print("Dataset Source:")
print("https://www.kaggle.com/datasets/ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training")

