# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QeBLEuXvANyaiU9vNQavu5q1-wXk86il
"""

!pip install tensorflow

!pip install matplotlib seaborn scikit-learn numpy

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ============================================
# LOAD CIFAR-10 DATASET
# ============================================

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Normalize images (0-255 → 0-1)
x_train = x_train / 255.0
x_test = x_test / 255.0

# Class labels
class_names = [
    'Airplane', 'Automobile', 'Bird', 'Cat',
    'Deer', 'Dog', 'Frog', 'Horse', 'Ship', 'Truck'
]

# ============================================
# DATA AUGMENTATION
# ============================================

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    zoom_range=0.1
)

datagen.fit(x_train)

# ============================================
# CNN MODEL
# ============================================

model = models.Sequential()

# First CNN Block
model.add(layers.Conv2D(32, (3,3), activation='relu',
                        input_shape=(32,32,3)))
model.add(layers.MaxPooling2D((2,2)))

# Second CNN Block
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

# Third CNN Block
model.add(layers.Conv2D(128, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

# Flatten
model.add(layers.Flatten())

# Dense Layers
model.add(layers.Dense(128, activation='relu'))

# Dropout
model.add(layers.Dropout(0.5))

# Output Layer
model.add(layers.Dense(10, activation='softmax'))

# ============================================
# MODEL SUMMARY
# ============================================

model.summary()

# ============================================
# COMPILE MODEL
# ============================================

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# ============================================
# TRAIN MODEL
# ============================================

history = model.fit(
    datagen.flow(x_train, y_train, batch_size=64),
    epochs=15,
    validation_data=(x_test, y_test)
)

# ============================================
# SAVE MODEL
# ============================================

model.save("saved_model/cnn_model.h5")

# ============================================
# EVALUATION
# ============================================

test_loss, test_accuracy = model.evaluate(x_test, y_test)

print("\nTest Accuracy:", test_accuracy)

# ============================================
# ACCURACY & LOSS GRAPH
# ============================================

plt.figure(figsize=(12,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy Curve')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss Curve')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

# ============================================
# PREDICTIONS
# ============================================

y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# ============================================
# CONFUSION MATRIX
# ============================================

cm = confusion_matrix(y_test, y_pred_classes)

plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

# ============================================
# CLASSIFICATION REPORT
# ============================================

print("\nClassification Report:\n")

print(classification_report(
    y_test,
    y_pred_classes,
    target_names=class_names
))

# ============================================
# PREDICTION VISUALIZATION
# ============================================

plt.figure(figsize=(15,10))

for i in range(12):
    plt.subplot(3,4,i+1)
    plt.imshow(x_test[i])

    true_label = class_names[int(y_test[i])]
    pred_label = class_names[y_pred_classes[i]]

    plt.title(f"True: {true_label}\nPred: {pred_label}")

    plt.axis('off')

plt.tight_layout()
plt.show()

