# -*- coding: utf-8 -*-
"""Heart_Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180ig6yktkTVKYtkTUOoY8wkEzRm_X8S-

#  Heart Disease Prediction - (Logistic Regression)
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("arezaei81/heartcsv")

print("Path to dataset files:", path)

"""## 1. Import Libraries"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    confusion_matrix, classification_report,
    roc_curve, auc
)

import joblib

"""## 2. Load Dataset"""

import os
df = pd.read_csv(os.path.join(path, "heart.csv"))
df.head()

"""## 3. Data Exploration"""

print(df.info())
print(df.describe())
print(df.isnull().sum())

sns.countplot(x='target', data=df)
plt.title("Target Distribution")
plt.show()

"""## 4. Visualization"""

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

sns.histplot(data=df, x='age', hue='target', kde=True)
plt.title("Age vs Heart Disease")
plt.show()

"""## 5. Preprocessing"""

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""## 6. Model Training"""

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

"""## 7. Prediction"""

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

"""## 8. Evaluation"""

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""## 9. Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

"""## 10. ROC Curve"""

fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label="AUC = %0.2f" % roc_auc)
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

"""## 11. Feature Importance"""

importance = pd.Series(model.coef_[0], index=X.columns)
importance.sort_values().plot(kind='barh')
plt.title("Feature Importance")
plt.show()

"""## 12. Save Model"""

joblib.dump(model, "heart_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model saved successfully!")

"""## 13. Custom Input Test"""

sample = np.array([[52,1,2,125,212,0,1,168,0,1.0,2,2,3]])
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

if prediction[0] == 1:
    print("⚠️ Heart Disease Detected")
else:
    print("✅ No Heart Disease")