# -*- coding: utf-8 -*-
"""linear_regression_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RU5xBvTIHequ6Rq1J9_8Hh_wjH5O0_xu

# Predictive Modeling using Linear Regression (Insurance Charges)

This notebook follows a clean, industry-style workflow:
- Exploratory Data Analysis (EDA)
- Preprocessing with ColumnTransformer
- Modeling with Pipeline
- Evaluation (MAE, MSE, R²)
- Interpretation (coefficients & insights)
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

print("Path to dataset files:", path)

# ===== Imports =====
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

sns.set(style='whitegrid')

"""## 1. Load Dataset"""

import os
df = pd.read_csv(os.path.join(path, 'insurance.csv'))
print('Shape:', df.shape)
df.head()

"""## 2. Basic EDA"""

df.info()
df.describe()
df.isnull().sum()

# Distribution of target variable
plt.figure(figsize=(6,4))
sns.histplot(df['charges'], kde=True)
plt.title('Distribution of Insurance Charges')
plt.xlabel('Charges')
plt.ylabel('Frequency')
plt.show()

# Correlation Heatmap
plt.figure(figsize=(8,5))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# Scatter with category insight
plt.figure(figsize=(6,4))
sns.scatterplot(x='bmi', y='charges', hue='smoker', data=df)
plt.title('BMI vs Charges (Smoker Impact)')
plt.show()

"""## 3. Feature Engineering & Split"""

X = df.drop('charges', axis=1)
y = df['charges']

num_cols = ['age', 'bmi', 'children']
cat_cols = ['sex', 'smoker', 'region']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""## 4. Preprocessing Pipelines"""

num_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder(drop='first'))
])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

"""## 5. Model Pipeline"""

model_pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('regressor', LinearRegression())
])

"""## 6. Train Model"""

model_pipeline.fit(X_train, y_train)
print('Model trained successfully 🚀')

"""## 7. Evaluation"""

y_pred = model_pipeline.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print('MAE:', mae)
print('MSE:', mse)
print('R2 Score:', r2)

"""## 8. Visualization: Actual vs Predicted"""

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred)
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted')
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color='red')
plt.show()

"""## 9. Interpretation (Feature Importance)"""

# Extract feature names after preprocessing
feature_names = model_pipeline.named_steps['preprocessing'].get_feature_names_out()

# Get coefficients
coefficients = model_pipeline.named_steps['regressor'].coef_

coef_df = pd.DataFrame({
    'Feature': feature_names,
    'Coefficient': coefficients
})

coef_df = coef_df.sort_values(by='Coefficient', ascending=False)
coef_df

plt.figure(figsize=(10, 6))
sns.barplot(x='Coefficient', y='Feature', data=coef_df, palette='viridis', hue='Feature', legend=False)
plt.title('Feature Coefficients (Impact on Insurance Charges)')
plt.xlabel('Coefficient Value')
plt.ylabel('Feature')
plt.show()

"""## 10. Key Insights"""

print('Insights:')
print('- Smoking has the strongest positive impact on charges.')
print('- Higher BMI leads to higher insurance cost.')
print('- Age also increases charges moderately.')