# -*- coding: utf-8 -*-
"""RandomForest_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1-aJqxcZPvsPXXoJmfoeUP62pInDGMm

# Predictive Modeling with Random Forest


### Introduction
This project uses the Titanic dataset to predict passenger survival (classification problem). The goal is to apply Random Forest to build a robust predictive model and analyze feature importance.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

"""### Load Dataset"""

df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.head()

"""### EDA Summary
- Dataset shape and missing values analyzed
- Basic visualization of survival distribution
"""

print(df.shape)
print(df.isnull().sum())
sns.countplot(x='Survived', data=df)
plt.show()

"""### Feature Engineering"""

df = df.drop(['Name','Ticket','Cabin'], axis=1)
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df = pd.get_dummies(df, drop_first=True)

"""### Train-Test Split"""

X = df.drop('Survived', axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""### Model Training"""

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
model.fit(X_train, y_train)

"""### Evaluation"""

y_pred = model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.show()

"""### Feature Importance"""

importances = model.feature_importances_
features = X.columns
feat_df = pd.DataFrame({'Feature': features, 'Importance': importances}).sort_values(by='Importance', ascending=False).head(10)
plt.barh(feat_df['Feature'], feat_df['Importance'])
plt.gca().invert_yaxis()
plt.show()

"""### Hyperparameter Tuning"""

param_grid = {'n_estimators':[100,200],'max_depth':[5,10,None]}
grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=3)
grid.fit(X_train, y_train)
print(grid.best_params_)

"""### Conclusion
- Model performs well with decent accuracy
- Most important features influence survival prediction
- Overfitting controlled using depth limit
"""